== Another simple example

Instead of using rtmp as a signal source, the following example uses srt.  (xref:NodeSettings.adoc[configuring the Norst playground for an srt source]) As with the earlier example (rtmp_to_rtc) the code extract does the following:

* Configures a single signal source (video and audio)
* Configures a target destination for the signal (RTC web server)
* Gets a connection to Norsk
** Gives Norsk source and target configurations
** Gives Norsk a callback function specifying that both audio and video are to be sent to the target.  Norsk will call this function when it has 'discovered' the sources given to it in the input configuration.


[source,TypeScript]
----
async function srt_to_rtc(argv: Arguments): Promise<void> {
  let srtInputSettings = {
    id: "srtInput",
    ip: argv.ip,
    port: argv.port,
    mode: SrtMode.PUSH,
    sourceName: "camera1",
  };

  let localRtcSettings = {
    id: "localRtcOutput",
    numVideoStreams: 1,
  };

  const norsk = new Norsk(baseUrl());
  let input = await norsk.input.srt(srtInputSettings);
  let localRtcOutput = await norsk.output.localWebRTC(localRtcSettings);
  localRtcOutput.subscribe([{ source: input, sourceSelector: selectAV }]);

}
----

As you can see, it is almost the same as our first example (rtmp_to_rtc), except that we are using a different video transmission protocol (srt) and therefore have different config to do - *and* we also call the srt constructor function on the norsk object, instead of rtmp. 