== Handling messages from Norsk

Revisiting the rtmp_to_rtc function, introduced on the previous page,the last line connected an audio-video source to a rtc web server

[source,TypeScript]
----
    // connect the web server receiver to the video input 
    localRtcOutput.subscribe([{ source: input, sourceSelector: selectAV }]);
----

The sourceSelector attribute references a callback function whose job it is to indicate which of a set of streams the Norsk Server has detected as inputs should be forwarded to the specified target(s).  When Norsk Server detects a change in the set of known inputs, it calls this function, providing details about each detected streams in a class called xref:NodeSettings.adoc[StreamMetadata]. This class has a function getStreamKey which returns an identifier for this stream, which is effectively a string aliased as its own type, which is xref:NodeSettings.adoc[StreamKey].  The callback function should return the StreamKey for each stream that it wants the Norsk server to forward to the target.  Speifically it should return an object containing up to three lists of streams, for audio, video, or subtitles.  Our sample app does not include subtitles.

Here is a sample function that does that

[source,TypeScript]
----
const selectAV(streams: StreamMetadata[]) => {
    const audioKeys = audioStreamKeys(streams);
    const videoKeys = videoStreamKeys(streams);
    if (audio.length == 1 && video.length == 1) {
      return { audio: audioKeys,
               video: videoKeys,
             };
    }
    return undefined;
  }
----

The logic implemented here is arbitrary, and in this case, simple.  It states that if Norsk indicates that it has exactly one audio and one video signal, then it should forward both streams.  However, you can implement any logic here that meets your business requirements, which might for example be to always favour a particular named stream if it is available.

The functions audioStreamKeys, and videoStreamKeys are simple helper functions on the sdk which filter the streams list to only those that are audio streams or video streams respectively.  There's also one called subtitleStreams.

===Setting stream keys

The key/identifier for each stream is set by you when you configure a stream source - in the example below it is "rtmpInput"
[source,TypeScript]
----
    let rtmpSettings = { id: "rtmpInput", port: argv.port };  
----
